<?zpl version="2.0"?>
<smil>
  <head>
    <meta name="totalDuration" content="32489528" />
    <meta name="itemCount" content="127" />
    <meta name="generator" content="Entertainment Platform -- 10.18091.1032.0" />
    <title>test</title>
  </head>
  <body>
    <seq>
      <media src="C:\Users\user\Music\iTunes\Ultravox\Premium Gold Collection\14 The Voice.m4a" albumTitle="Premium Gold Collection" albumArtist="Ultravox" trackTitle="The Voice" trackArtist="Ultravox" duration="264568" />
      <media src="C:\Users\user\Music\iTunes\Wham\Album sconosciuto\Last Christmas.mp3" albumTitle="The Final" albumArtist="Wham!" trackTitle="Last Christmas" trackArtist="Wham" duration="405890" />
      <media src="C:\Users\user\Music\iTunes\The Who\The Ultimate Collection [Disc 1]\1-03 My Generation.m4a" albumTitle="The Ultimate Collection [Disc 1]" albumArtist="The Who" trackTitle="My Generation" trackArtist="The Who" duration="199389" />
      <media src="C:\Users\user\Music\iTunes\The Style Council\Our Favourite Shop\07 Boy Who Cried Wolf.m4a" albumTitle="Our Favourite Shop" albumArtist="The Style Council" trackTitle="Boy Who Cried Wolf" trackArtist="The Style Council" duration="315048" />
      <media src="C:\Users\user\Music\iTunes\The Style Council\Our Favourite Shop\15 Shout To The Top.m4a" albumTitle="Our Favourite Shop" albumArtist="The Style Council" trackTitle="Shout To The Top" trackArtist="The Style Council" duration="261433" />
      <media src="C:\Users\user\Music\iTunes\The Smiths\The Best Of The Smiths, Vol. 2\14 There Is A Light That Never Goes.mp3" albumTitle="The Best Of The Smiths, Vol. 2" albumArtist="The Smiths" trackTitle="There Is A Light That Never Goes Out" trackArtist="The Smiths" duration="243043" />
      <media src="C:\Users\user\Music\iTunes\The Strokes\Is This It_\05 Someday.m4a" albumTitle="Is This It?" albumArtist="The Strokes" trackTitle="Someday" trackArtist="The Strokes" duration="187199" />
      <media src="C:\Users\user\Music\iTunes\The Smiths\The Best Of The Smiths, Vol. 2\04 Ask.mp3" albumTitle="The Best Of The Smiths, Vol. 2" albumArtist="The Smiths" trackTitle="Ask" trackArtist="The Smiths" duration="191712" />
      <media src="C:\Users\user\Music\iTunes\The Smiths\The Best Of The Smiths, Vol. 2\08 Bigmouth Strikes Again.mp3" albumTitle="The Best Of The Smiths, Vol. 2" albumArtist="The Smiths" trackTitle="Bigmouth Strikes Again" trackArtist="The Smiths" duration="193828" />
      <media src="C:\Users\user\Music\iTunes\The Cure\Staring At The Sea_ The Singles 1979-198\03 Boys Don't Cry.mp3" albumTitle="Staring At The Sea: The Singles 1979-1985" albumArtist="The Cure" trackTitle="Boys Don't Cry" trackArtist="The Cure" duration="155089" />
      <media src="C:\Users\user\Music\iTunes\The Pasadena's\Fetenkult - Black Party 2-2\15 Tribute (Right On).mp3" albumTitle="Fetenkult - Black Party 2-2" albumArtist="The Pasadenas" trackTitle="Tribute (Right On)" trackArtist="The Pasadena's" duration="264071" />
      <media src="C:\Users\user\Music\iTunes\The Cure\Staring At The Sea_ The Singles 1979-198\15 In Between Days.mp3" albumTitle="Staring At The Sea: The Singles 1979-1985" albumArtist="The Cure" trackTitle="In Between Days" trackArtist="The Cure" duration="176744" />
      <media src="C:\Users\user\Music\iTunes\The Cure\Staring At The Sea_ The Singles 1979-198\16 Close To Me.mp3" albumTitle="Staring At The Sea: The Singles 1979-1985" albumArtist="The Cure" trackTitle="Close To Me" trackArtist="The Cure" duration="220577" />
      <media src="C:\Users\user\Music\iTunes\The Cranberries\To The Faithful Departed\02 Salvation.mp3" albumTitle="To The Faithful Departed" albumArtist="The Cranberries" trackTitle="Salvation" trackArtist="The Cranberries" duration="143986" />
      <media src="C:\Users\user\Music\iTunes\Texas\Soundtrack - Bend it Like Beckham\14 Inner Smile.mp3" albumTitle="Soundtrack - Bend it Like Beckham" albumArtist="Various Artists" trackTitle="Inner Smile" trackArtist="Texas" duration="230582" />
      <media src="C:\Users\user\Music\iTunes\Terence Trent D'Arby\Introducing The Hardline According To Te\05 Dance Little Sister.mp3" albumTitle="Introducing The Hardline According To Terence Trent D'Arby" albumArtist="Terence Trent D'Arby" trackTitle="Dance Little Sister" trackArtist="Terence Trent D'Arby" duration="234684" />
      <media src="C:\Users\user\Music\iTunes\Tears For Fears\Tears Roll Down (Greatest Hits 82-92)\11 Change.m4a" albumTitle="Tears Roll Down (Greatest Hits 82-92)" albumArtist="Tears for Fears" trackTitle="Change" trackArtist="Tears for Fears" duration="234730" />
      <media src="C:\Users\user\Music\iTunes\Subsonica\Tutti I Miei Sbagli _(Italian EP)\01 Tutti I Miei Sbagli.m4a" albumTitle="Tutti I Miei Sbagli _(Italian EP)" albumArtist="Subsonica" trackTitle="Tutti I Miei Sbagli" trackArtist="Subsonica" duration="245388" />
      <media src="C:\Users\user\Music\iTunes\Talk Talk\It's My Life\02 Such A Shame.m4a" albumTitle="It's My Life" albumArtist="Talk Talk" trackTitle="Such A Shame" trackArtist="Talk Talk" duration="335598" />
      <media src="C:\Users\user\Music\iTunes\Simple Minds\New Gold Dream\New Gold Dream.mp3" albumTitle="New Gold Dream" albumArtist="Classique Rock de Systeme 21" trackTitle="New Gold Dream" trackArtist="Simple Minds" duration="337759" />
      <media src="C:\Users\user\Music\iTunes\sean paul\Album sconosciuto\Baby boy.mp3" albumTitle="Dutty Rock" albumArtist="Sean Paul" trackTitle="Baby boy" trackArtist="Sean Paul" duration="244924" />
      <media src="C:\Users\user\Music\iTunes\Sade\Stronger Than Pride\03 Nothing Can Come Between Us.m4a" albumTitle="Stronger Than Pride" albumArtist="Sade" trackTitle="Nothing Can Come Between Us" trackArtist="Sade" duration="264359" />
      <media src="C:\Users\user\Music\iTunes\Rihanna\Rihanna\01 Pon De Replay.mp3" albumTitle="Rihanna" albumArtist="Rihanna" trackTitle="Pon De Replay" trackArtist="Rihanna" duration="257525" />
      <media src="C:\Users\user\Music\iTunes\R.E.M_\The Best Of R.E.M. In Time 1988-2003\06 Losing my religion.mp3" albumTitle="The Best Of R.E.M. In Time 1988-2003" albumArtist="R.E.M." trackTitle="Losing my religion" trackArtist="R.E.M." duration="269035" />
      <media src="C:\Users\user\Music\iTunes\R.E.M_\The Best Of R.E.M. In Time 1988-2003\13 Stand.mp3" albumTitle="The Best Of R.E.M. In Time 1988-2003" albumArtist="R.E.M." trackTitle="Stand" trackArtist="R.E.M." duration="192208" />
      <media src="C:\Users\user\Music\iTunes\Pino Daniele\Napule E' [Disc 1]\13 Je So Pazzo.mp3" albumTitle="Napule E' [Disc 1]" albumArtist="Pino Daniele" trackTitle="Je So Pazzo" trackArtist="Pino Daniele" duration="222876" />
      <media src="C:\Users\user\Music\iTunes\Nirvana\Nevermind\05 Lithium.mp3" albumTitle="Nevermind" albumArtist="Nirvana" trackTitle="Lithium" trackArtist="Nirvana" duration="257044" />
      <media src="C:\Users\user\Music\iTunes\Pink\Album sconosciuto\01 Get This Party Started.mp3" albumTitle="M!ssundaztood" albumArtist="P!nk" trackTitle="Get This Party Started" trackArtist="Pink" duration="194115" />
      <media src="C:\Users\user\Music\iTunes\Nirvana\Nevermind\01 Smells Like Teen Spirit.mp3" albumTitle="Nevermind" albumArtist="Nirvana" trackTitle="Smells Like Teen Spirit" trackArtist="Nirvana" duration="301191" />
      <media src="C:\Users\user\Music\iTunes\Nirvana\Nevermind\03 Come As You Are.mp3" albumTitle="Nevermind" albumArtist="Nirvana" trackTitle="Come As You Are" trackArtist="Nirvana" duration="219115" />
      <media src="C:\Users\user\Music\iTunes\Natalie Imbruglia\Left Of The Middle\01 Torn.mp3" albumTitle="Left Of The Middle" albumArtist="Natalie Imbruglia" trackTitle="Torn" trackArtist="Natalie Imbruglia" duration="244976" />
      <media src="C:\Users\user\Music\iTunes\Macy Gray\On How Life Is\02 Do Something.mp3" albumTitle="On How Life Is" albumArtist="Macy Gray" trackTitle="Do Something" trackArtist="Macy Gray" duration="299990" />
      <media src="C:\Users\user\Music\iTunes\Lucio Battisti\Pensieri, Emozioni (Cd 2°)\10 Ancora Tu.mp3" albumTitle="Pensieri, Emozioni (Cd 2°)" albumArtist="Lucio Battisti" trackTitle="Ancora Tu" trackArtist="Lucio Battisti" duration="281129" />
      <media src="C:\Users\user\Music\iTunes\Lenny Kravitz\Mama Said\04 It Ain't Over 'Til It's Over.mp3" albumTitle="Mama Said" albumArtist="Lenny Kravitz" trackTitle="It Ain't Over 'Til It's Over" trackArtist="Lenny Kravitz" duration="242625" />
      <media src="C:\Users\user\Music\iTunes\Linkin Park\Hybrid Theory\08 In The End.mp3" albumTitle="Hybrid Theory" albumArtist="Linkin Park" trackTitle="In The End" trackArtist="Linkin Park" duration="216346" />
      <media src="C:\Users\user\Music\iTunes\Lenny Kravitz\Are You Gonna Go My Way\01 Are You Gonna Go My Way.mp3" albumTitle="Are You Gonna Go My Way" albumArtist="Lenny Kravitz" trackTitle="Are You Gonna Go My Way" trackArtist="Lenny Kravitz" duration="212323" />
      <media src="C:\Users\user\Music\iTunes\Joy Division\Unknown Pleasures\01 Disorder.mp3" albumTitle="Unknown Pleasures" albumArtist="Joy Division" trackTitle="Disorder" trackArtist="Joy Division" duration="212112" />
      <media src="C:\Users\user\Music\iTunes\Kool &amp; The Gang\Greatest Hits\02 Let's Go Dancin' (Oah La, La, La).m4a" albumTitle="Greatest Hits" albumArtist="kool and the gang" trackTitle="Let's Go Dancin' (Oah La, La, La)" trackArtist="Kool &amp; The Gang" duration="400637" />
      <media src="C:\Users\user\Music\iTunes\Kool &amp; The Gang\Greatest Hits\10 Get Down On It.m4a" albumTitle="Greatest Hits" albumArtist="kool and the gang" trackTitle="Get Down On It" trackArtist="Kool &amp; The Gang" duration="295102" />
      <media src="C:\Users\user\Music\iTunes\Lenny Kravitz\5\03 I Belong To You.mp3" albumTitle="5" albumArtist="Lenny Kravitz" trackTitle="I Belong To You" trackArtist="Lenny Kravitz" duration="257645" />
      <media src="C:\Users\user\Music\iTunes\James Taylor Quartet\Wait A Minute\06 Theme From 'Starsky &amp; Hutch' (fun.m4a" albumTitle="Wait A Minute" albumArtist="The James Taylor Quartet" trackTitle="Theme From 'Starsky &amp; Hutch' (funky people mix)" trackArtist="James Taylor Quartet" duration="356751" />
      <media src="C:\Users\user\Music\iTunes\Jamiroquai\Synkronized\01 Canned Heat.m4a" albumTitle="Synkronized" albumArtist="Jamiroquai" trackTitle="Canned Heat" trackArtist="Jamiroquai" duration="331813" />
      <media src="C:\Users\user\Music\iTunes\Incognito\Remixed\08 Always There (David Morales Remix.mp3" albumTitle="Remixed" albumArtist="Incognito" trackTitle="Always There (David Morales Remix)" trackArtist="Incognito" duration="396773" />
      <media src="C:\Users\user\Music\iTunes\Incognito\Remixed\02 Good Love (CJ'ss 12_ Remix).mp3" albumTitle="Remixed" albumArtist="Incognito" trackTitle="Good Love (CJ'ss 12&quot; Remix)" trackArtist="Incognito" duration="353123" />
      <media src="C:\Users\user\Music\iTunes\Incognito\Remixed\09 Givin' It Up (Roger Sanchez Uplif.mp3" albumTitle="Remixed" albumArtist="Incognito" trackTitle="Givin' It Up (Roger Sanchez Uplifting Club Mix)" trackArtist="Incognito" duration="365609" />
      <media src="C:\Users\user\Music\iTunes\James Taylor Quartet\In The Hand Of The Inevitable\01 Love Will Keep Us Together.m4a" albumTitle="In The Hand Of The Inevitable" albumArtist="James Taylor Quartet" trackTitle="Love Will Keep Us Together" trackArtist="James Taylor Quartet" duration="367966" />
      <media src="C:\Users\user\Music\iTunes\Jamiroquai\Emergency On Planet Earth\01 When You Gonna Learn (Digeridoo).m4a" albumTitle="Emergency On Planet Earth" albumArtist="Jamiroquai" trackTitle="When You Gonna Learn (Digeridoo)" trackArtist="Jamiroquai" duration="230597" />
      <media src="C:\Users\user\Music\iTunes\Jamiroquai\Emergency On Planet Earth\02 Too Young To Die.m4a" albumTitle="Emergency On Planet Earth" albumArtist="Jamiroquai" trackTitle="Too Young To Die" trackArtist="Jamiroquai" duration="365783" />
      <media src="C:\Users\user\Music\iTunes\Jamiroquai\Emergency On Planet Earth\08 Blow Your Mind.m4a" albumTitle="Emergency On Planet Earth" albumArtist="Jamiroquai" trackTitle="Blow Your Mind" trackArtist="Jamiroquai" duration="512301" />
      <media src="C:\Users\user\Music\iTunes\Giorgia\Album sconosciuto\Nessun dolore.mp3" albumTitle="Giorgia" albumArtist="Giorgia" trackTitle="Nessun dolore" trackArtist="Giorgia" duration="267258" />
      <media src="C:\Users\user\Music\iTunes\Green Day\American Idiot\Holiday.mp3" albumTitle="American Idiot" albumArtist="Green Day" trackTitle="Holiday" trackArtist="Green Day" duration="232698" />
      <media src="C:\Users\user\Music\iTunes\Eurythmics\Ultimate Collection\05 Right By Your Side.mp3" albumTitle="Ultimate Collection" albumArtist="Eurythmics" trackTitle="Right By Your Side" trackArtist="Eurythmics" duration="230530" />
      <media src="C:\Users\user\Music\iTunes\Eurythmics\Ultimate Collection\14 Missionary Man.mp3" albumTitle="Ultimate Collection" albumArtist="Eurythmics" trackTitle="Missionary Man" trackArtist="Eurythmics" duration="228388" />
      <media src="C:\Users\user\Music\iTunes\Fatboy Slim\The Chillout Album (Disc 1)\1-03 Praise You.m4a" albumTitle="The Chillout Album (Disc 1)" albumArtist="Various Artists" trackTitle="Praise You" trackArtist="Fatboy Slim" duration="323059" />
      <media src="C:\Users\user\Music\iTunes\Eurythmics\Ultimate Collection\03 Sweet Dreams (Are Made Of This).mp3" albumTitle="Ultimate Collection" albumArtist="Eurythmics" trackTitle="Sweet Dreams (Are Made Of This)" trackArtist="Eurythmics" duration="217965" />
      <media src="C:\Users\user\Music\iTunes\Elvis Presley\Selection Of (Disc 1)\01 Jailhouse Rock.m4a" albumTitle="Selection Of (Disc 1)" albumArtist="Elvis Presley" trackTitle="Jailhouse Rock" trackArtist="Elvis Presley" duration="162400" />
      <media src="C:\Users\user\Music\iTunes\Elvis Presley\Selection Of (Disc 1)\04 Tutti Frutti.m4a" albumTitle="Selection Of (Disc 1)" albumArtist="Elvis Presley" trackTitle="Tutti Frutti" trackArtist="Elvis Presley" duration="123506" />
      <media src="C:\Users\user\Music\iTunes\Duran Duran\Album sconosciuto\Save a Prayer.mp3" albumTitle="Rio" albumArtist="Duran Duran" trackTitle="Save a Prayer" trackArtist="Duran Duran" duration="327209" />
      <media src="C:\Users\user\Music\iTunes\Earth Wind &amp; Fire\Let's Groove (A Dance Collection)\01 Fantasy.m4a" albumTitle="Let's Groove (A Dance Collection)" albumArtist="Earth, Wind &amp; Fire" trackTitle="Fantasy" trackArtist="Earth Wind &amp; Fire" duration="281007" />
      <media src="C:\Users\user\Music\iTunes\Earth Wind &amp; Fire\Let's Groove (A Dance Collection)\05 Boogie Wonderland.m4a" albumTitle="Let's Groove (A Dance Collection)" albumArtist="Earth, Wind &amp; Fire" trackTitle="Boogie Wonderland" trackArtist="Earth Wind &amp; Fire" duration="290342" />
      <media src="C:\Users\user\Music\iTunes\Earth Wind &amp; Fire\Let's Groove (A Dance Collection)\08 September.m4a" albumTitle="Let's Groove (A Dance Collection)" albumArtist="Earth, Wind &amp; Fire" trackTitle="September" trackArtist="Earth Wind &amp; Fire" duration="217733" />
      <media src="C:\Users\user\Music\iTunes\Earth Wind &amp; Fire\Let's Groove (A Dance Collection)\09 Let's Groove.m4a" albumTitle="Let's Groove (A Dance Collection)" albumArtist="Earth, Wind &amp; Fire" trackTitle="Let's Groove" trackArtist="Earth Wind &amp; Fire" duration="339220" />
      <media src="C:\Users\user\Music\iTunes\Duran Duran\Album sconosciuto\The Reflex.mp3" albumTitle="Greatest" albumArtist="Duran Duran" trackTitle="The Reflex" trackArtist="Duran Duran" duration="266083" />
      <media src="C:\Users\user\Music\iTunes\Destinys Child\The Writing On The Wall\Say My Name.mp3" albumTitle="The Writing On The Wall" albumArtist="Destiny's Child" trackTitle="Say My Name" trackArtist="Destinys Child" duration="270979" />
      <media src="C:\Users\user\Music\iTunes\Depeche Mode\The Singles 86_98 (Disc 2)\11 Everything Counts (Live).mp3" albumTitle="The Singles 86>98 (Disc 2)" albumArtist="Depeche Mode" trackTitle="Everything Counts (Live)" trackArtist="Depeche Mode" duration="398053" />
      <media src="C:\Users\user\Music\iTunes\Dire Straits\Making Movies\01 Tunnel Of Love.mp3" albumTitle="Making Movies" albumArtist="Dire Straits" trackTitle="Tunnel Of Love" trackArtist="Dire Straits" duration="491493" />
      <media src="C:\Users\user\Music\iTunes\Depeche Mode\The Singles 81-85\07 Get The Balance Right.mp3" albumTitle="The Singles 81-85" albumArtist="Depeche Mode" trackTitle="Get The Balance Right" trackArtist="Depeche Mode" duration="195056" />
      <media src="C:\Users\user\Music\iTunes\Depeche Mode\Singles 1986-1998 (Disc 1)\07 Personal Jesus.mp3" albumTitle="Singles 1986-1998 (Disc 1)" albumArtist="Depeche Mode" trackTitle="Personal Jesus" trackArtist="Depeche Mode" duration="226429" />
      <media src="C:\Users\user\Music\iTunes\Depeche Mode\Singles 1986-1998 (Disc 1)\08 Enjoy The Silence.mp3" albumTitle="Singles 1986-1998 (Disc 1)" albumArtist="Depeche Mode" trackTitle="Enjoy The Silence" trackArtist="Depeche Mode" duration="256809" />
      <media src="C:\Users\user\Music\iTunes\Depeche Mode\Playing The Angel\05 Precious.mp3" albumTitle="Playing The Angel" albumArtist="Depeche Mode" trackTitle="Precious" trackArtist="Depeche Mode" duration="250200" />
      <media src="C:\Users\user\Music\iTunes\Craig David\www.mp3utopia.co.uk\Seven Days.mp3" albumTitle="www.mp3utopia.co.uk" albumArtist="Craig David" trackTitle="Seven Days" trackArtist="Craig David" duration="231523" />
      <media src="C:\Users\user\Music\iTunes\David Bowie\Changesbowie\08 Rebel Rebel.mp3" albumTitle="Changesbowie" albumArtist="David Bowie" trackTitle="Rebel Rebel" trackArtist="David Bowie" duration="271621" />
      <media src="C:\Users\user\Music\iTunes\David Bowie\Changesbowie\12 Heroes.mp3" albumTitle="Changesbowie" albumArtist="David Bowie" trackTitle="Heroes" trackArtist="David Bowie" duration="218409" />
      <media src="C:\Users\user\Music\iTunes\David Bowie\Changesbowie\15 Let's Dance.mp3" albumTitle="Changesbowie" albumArtist="David Bowie" trackTitle="Let's Dance" trackArtist="David Bowie" duration="250566" />
      <media src="C:\Users\user\Music\iTunes\David Bowie\Changesbowie\18 Blue Jean.mp3" albumTitle="Changesbowie" albumArtist="David Bowie" trackTitle="Blue Jean" trackArtist="David Bowie" duration="190066" />
      <media src="C:\Users\user\Music\iTunes\Compilation\W Hotel\03 Got To Give It Up.m4a" albumTitle="W Hotel" albumArtist="Various Artists" trackTitle="Got To Give It Up" trackArtist="Marvin Gaye" duration="252029" />
      <media src="C:\Users\user\Music\iTunes\Compilation\W Hotel\06 Whatcha See Is Whatcha Get.m4a" albumTitle="W Hotel" albumArtist="Various Artists" trackTitle="Whatcha See Is Whatcha Get" trackArtist="The Dramatics" duration="235868" />
      <media src="C:\Users\user\Music\iTunes\Cool and the gang\Album sconosciuto\GET DOWN ON IT.mp3" albumTitle="The Very Best of Kool &amp; the Gang" albumArtist="Kool &amp; The Gang" trackTitle="GET DOWN ON IT" trackArtist="Cool and the gang" duration="291082" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Travelling Without Moving\02 Cosmic Girl.m4a" albumTitle="Travelling Without Moving" albumArtist="Jamiroquai" trackTitle="Cosmic Girl" trackArtist="Jamiroquai" duration="243995" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Singles Collection 1984-1990\01 Smalltown Boy.m4a" albumTitle="The Singles Collection 1984-1990" albumArtist="Jimmy Somerville" trackTitle="Smalltown Boy" trackArtist="Bronski Beat" duration="301116" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Singles Collection 1984-1990\07 Never Can Say Goodbye.m4a" albumTitle="The Singles Collection 1984-1990" albumArtist="Jimmy Somerville" trackTitle="Never Can Say Goodbye" trackArtist="The Communards" duration="268469" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Singles Collection 1984-1990\09 You Are My World.m4a" albumTitle="The Singles Collection 1984-1990" albumArtist="Jimmy Somerville" trackTitle="You Are My World" trackArtist="The Communards" duration="271789" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Singles Collection 1984-1990\16 Disenchanted.m4a" albumTitle="The Singles Collection 1984-1990" albumArtist="Jimmy Somerville" trackTitle="Disenchanted" trackArtist="The Communards" duration="250729" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Big Chill\03 Good Lovin'.m4a" albumTitle="The Big Chill" albumArtist="Soundtrack" trackTitle="Good Lovin'" trackArtist="The Rascals" duration="150395" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Big Chill\06 Ain't Too Proud To Beg.m4a" albumTitle="The Big Chill" albumArtist="Soundtrack" trackTitle="Ain't Too Proud To Beg" trackArtist="The Temptations" duration="153228" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Big Chill\09 A Whiter Shade Of Pale.m4a" albumTitle="The Big Chill" albumArtist="Soundtrack" trackTitle="A Whiter Shade Of Pale" trackArtist="Procol Harum" duration="245760" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Big Chill\01 I Heard It Through The Grapevine.m4a" albumTitle="The Big Chill" albumArtist="Soundtrack" trackTitle="I Heard It Through The Grapevine" trackArtist="Marvin Gaye" duration="303020" />
      <media src="C:\Users\user\Music\iTunes\Compilation\The Big Chill\02 My Girl.m4a" albumTitle="The Big Chill" albumArtist="Soundtrack" trackTitle="My Girl" trackArtist="The Temptations" duration="177586" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Soul Power - The Very Best Of Rhythm &amp; B\1-17 Green Onions.m4a" albumTitle="Soul Power - The Very Best Of Rhythm &amp; Blues (Disc 1)" albumArtist="Divers" trackTitle="Green Onions" trackArtist="Booker T. &amp; The MG's" duration="171084" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Soul Power - The Very Best Of Rhythm &amp; B\2-04 I Got A Woman.m4a" albumTitle="Soul Power - The Very Best Of Rhythm &amp; Blues" albumArtist="Various Artists" trackTitle="I Got A Woman" trackArtist="Ray Charles" duration="172129" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Soul Power - The Very Best Of Rhythm &amp; B\2-07 (You Make Me Feel Like) A Natur.m4a" albumTitle="Soul Power - The Very Best Of Rhythm &amp; Blues" albumArtist="Various Artists" trackTitle="(You Make Me Feel Like) A Natural Woman" trackArtist="Aretha Franklin" duration="161634" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Soul Power - The Very Best Of Rhythm &amp; B\2-09 What'd I Say (Part 1 &amp; 2).m4a" albumTitle="Soul Power - The Very Best Of Rhythm &amp; Blues" albumArtist="Various Artists" trackTitle="What'd I Say (Part 1 &amp; 2)" trackArtist="Ray Charles" duration="388771" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Soul Power - The Very Best Of Rhythm &amp; B\2-13 Think.m4a" albumTitle="Soul Power - The Very Best Of Rhythm &amp; Blues" albumArtist="Various Artists" trackTitle="Think" trackArtist="Aretha Franklin" duration="136347" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Soul Power - The Very Best Of Rhythm &amp; B\2-14 I've Been Loving You Too Long.m4a" albumTitle="Soul Power - The Very Best Of Rhythm &amp; Blues" albumArtist="Various Artists" trackTitle="I've Been Loving You Too Long" trackArtist="Otis Redding" duration="193097" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Soul Power - The Very Best Of Rhythm &amp; B\2-15 When A Man Loves A Woman.m4a" albumTitle="Soul Power - The Very Best Of Rhythm &amp; Blues" albumArtist="Various Artists" trackTitle="When A Man Loves A Woman" trackArtist="Percy Sledge" duration="170666" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Rhythms Del Mundo_ Cuba\10 Ai No Corrida.m4a" albumTitle="Rhythms Del Mundo: Cuba" albumArtist="Rhythms del Mundo" trackTitle="Ai No Corrida" trackArtist="Vania Borges Feat. Quincy Jones" duration="270582" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Hard Candy\03 Give It 2 Me.m4a" albumTitle="Hard Candy" albumArtist="Madonna" trackTitle="Give It 2 Me" trackArtist="Madonna" duration="287973" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Hard Candy\08 Beat Goes On.m4a" albumTitle="Hard Candy" albumArtist="Madonna" trackTitle="Beat Goes On" trackArtist="Madonna Feat. Kanye West" duration="266959" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Good Girl Gone Bad\01 Umbrella.m4a" albumTitle="Good Girl Gone Bad" albumArtist="Rihanna" trackTitle="Umbrella" trackArtist="Rihanna Feat. Jay-Z" duration="278105" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Good Girl Gone Bad\03 Don't Stop The Music.m4a" albumTitle="Good Girl Gone Bad" albumArtist="Rihanna" trackTitle="Don't Stop The Music" trackArtist="Rihanna" duration="269212" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Forrest Gump [Disc 2] [Bonus Tracks]\2-04 Turn! Turn! Turn! (To Everythin.m4a" albumTitle="Forrest Gump [Disc 2] [Bonus Tracks]" albumArtist="Various Artists" trackTitle="Turn! Turn! Turn! (To Everything There Is A Season)" trackArtist="The Byrds" duration="234730" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Forrest Gump [Disc 2] [Bonus Tracks]\2-11 Sweet Home Alabama.m4a" albumTitle="Forrest Gump [Disc 2] [Bonus Tracks]" albumArtist="Various Artists" trackTitle="Sweet Home Alabama" trackArtist="Lynyrd Skynyrd" duration="283771" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Forrest Gump [Disc 1]\1-09 Catch Me If You Can.m4a" albumTitle="Forrest Gump [Disc 1]" albumArtist="Various Artists" trackTitle="Catch Me If You Can" trackArtist="Aretha Franklin" duration="147423" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Forrest Gump [Disc 1]\1-12 Danny Boy.m4a" albumTitle="Forrest Gump [Disc 1]" albumArtist="Various Artists" trackTitle="Danny Boy" trackArtist="The Mamas &amp; The Papas" duration="159474" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Forrest Gump [Disc 1]\1-13 For What It's Worth.m4a" albumTitle="Forrest Gump [Disc 1]" albumArtist="Various Artists" trackTitle="For What It's Worth" trackArtist="Buffalo Springfield" duration="158638" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Forrest Gump [Disc 1]\1-15 Break On Through (To The Other.m4a" albumTitle="Forrest Gump [Disc 1]" albumArtist="Various Artists" trackTitle="Break On Through (To The Other Side)" trackArtist="The Doors" duration="147075" />
      <media src="C:\Users\user\Music\iTunes\Compilation\FM Radio Evolution 5 - The British Invas\04 Doot Doot.m4a" albumTitle="FM Radio Evolution 5 - The British Invasion" albumArtist="Various Artists" trackTitle="Doot Doot" trackArtist="Freur" duration="241092" />
      <media src="C:\Users\user\Music\iTunes\Compilation\FM Radio Evolution 5 - The British Invas\05 Too Shy.m4a" albumTitle="FM Radio Evolution 5 - The British Invasion" albumArtist="Various Artists" trackTitle="Too Shy" trackArtist="Kajagoogoo" duration="222284" />
      <media src="C:\Users\user\Music\iTunes\Compilation\FM Radio Evolution 5 - The British Invas\08 Let Me Go.m4a" albumTitle="FM Radio Evolution 5 - The British Invasion" albumArtist="Various Artists" trackTitle="Let Me Go" trackArtist="Heaven 17" duration="257253" />
      <media src="C:\Users\user\Music\iTunes\Compilation\FM Radio Evolution 5 - The British Invas\09 What Is Love_.m4a" albumTitle="FM Radio Evolution 5 - The British Invasion" albumArtist="Various Artists" trackTitle="What Is Love?" trackArtist="Howard Jones" duration="219475" />
      <media src="C:\Users\user\Music\iTunes\Compilation\FM Radio Evolution 5 - The British Invas\10 Wouldn't It Be Good.m4a" albumTitle="FM Radio Evolution 5 - The British Invasion" albumArtist="Various Artists" trackTitle="Wouldn't It Be Good" trackArtist="Nik Kershaw" duration="264289" />
      <media src="C:\Users\user\Music\iTunes\Compilation\FM Radio Evolution 5 - The British Invas\11 Dance Hall Days.m4a" albumTitle="FM Radio Evolution 5 - The British Invasion" albumArtist="Various Artists" trackTitle="Dance Hall Days" trackArtist="Wang Chung" duration="237284" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Easy Rider\01 The Pusher.m4a" albumTitle="Easy Rider" albumArtist="Soundtrack" trackTitle="The Pusher" trackArtist="Steppenwolf" duration="353291" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Easy Rider\02 Born To Be Wild.m4a" albumTitle="Easy Rider" albumArtist="Soundtrack" trackTitle="Born To Be Wild" trackArtist="Steppenwolf" duration="220241" />
      <media src="C:\Users\user\Music\iTunes\Compilation\Definitive Collection\05 Oye Como Va.m4a" albumTitle="Definitive Collection" albumArtist="Santana" trackTitle="Oye Como Va" trackArtist="Santana" duration="256789" />
      <media src="C:\Users\user\Music\iTunes\Coldplay\X&amp;Y\07 Speed Of Sound.mp3" albumTitle="X&amp;Y" albumArtist="Coldplay" trackTitle="Speed Of Sound" trackArtist="Coldplay" duration="288496" />
      <media src="C:\Users\user\Music\iTunes\Coldplay\Viva La Vida Or Death And All His Friend\07 Viva La Vida.m4a" albumTitle="Viva La Vida Or Death And All His Friends" albumArtist="Coldplay" trackTitle="Viva La Vida" trackArtist="Coldplay" duration="241487" />
      <media src="C:\Users\user\Music\iTunes\Coldplay\A Rush Of Blood To The Head\05 Clocks.mp3" albumTitle="A Rush Of Blood To The Head" albumArtist="Coldplay" trackTitle="Clocks" trackArtist="Coldplay" duration="307513" />
      <media src="C:\Users\user\Music\iTunes\Chicane\The Chillout Album (Disc 1)\1-06 Offshore.m4a" albumTitle="The Chillout Album (Disc 1)" albumArtist="Various Artists" trackTitle="Offshore" trackArtist="Chicane" duration="406790" />
      <media src="C:\Users\user\Music\iTunes\Carmen Consoli\In Bianco E Nero\01 In Bianco E Nero.mp3" albumTitle="In Bianco E Nero" albumArtist="Bianca Atzei" trackTitle="In Bianco E Nero" trackArtist="Carmen Consoli" duration="227552" />
      <media src="C:\Users\user\Music\iTunes\Bryan Ferry - Roxy Music\Street Life - 20 Great Hits\17 More Than This.mp3" albumTitle="Street Life - 20 Great Hits" albumArtist="Roxy Music" trackTitle="More Than This" trackArtist="Bryan Ferry - Roxy Music" duration="250409" />
      <media src="C:\Users\user\Music\iTunes\Buena Vista Social Club\Buena Vista Social Club\09 Candela.m4a" albumTitle="Buena Vista Social Club" albumArtist="Buena Vista Social Club" trackTitle="Candela" trackArtist="Buena Vista Social Club" duration="329258" />
      <media src="C:\Users\user\Music\iTunes\Bran Van 3000\Album sconosciuto\Drinking In L.A..mp3" albumTitle="Glee" albumArtist="Bran Van 3000" trackTitle="Drinking In L.A." trackArtist="Bran Van 3000" duration="235702" />
      <media src="C:\Users\user\Music\iTunes\Björk\Debut\10 Violently Happy.mp3" albumTitle="Debut" albumArtist="Björk" trackTitle="Violently Happy" trackArtist="Björk" duration="299311" />
      <media src="C:\Users\user\Music\iTunes\Bill Withers\Bill Withers Greatest Hits\01 Just The Two Of Us.m4a" albumTitle="Bill Withers Greatest Hits" albumArtist="Bill Withers" trackTitle="Just The Two Of Us" trackArtist="Bill Withers" duration="238817" />
      <media src="C:\Users\user\Music\iTunes\Bill Withers\Bill Withers Greatest Hits\03 Ain't No Sunshine.m4a" albumTitle="Bill Withers Greatest Hits" albumArtist="Bill Withers" trackTitle="Ain't No Sunshine" trackArtist="Bill Withers" duration="126316" />
      <media src="C:\Users\user\Music\iTunes\Bill Withers\Bill Withers Greatest Hits\04 Lovely Day.m4a" albumTitle="Bill Withers Greatest Hits" albumArtist="Bill Withers" trackTitle="Lovely Day" trackArtist="Bill Withers" duration="257230" />
    </seq>
  </body>
</smil>